openapi: 3.1.0
info:
  description: <p>Contains all available API endpoints in this codebase</p>
  version: 1.0.0
  title: Bank Argent API documentation
  contact:
    name: Api Support
    email: leiroz26@hotmail.com
  termsOfService: http://swagger.io/terms/
servers:
  - url: http://localhost:3001/api/v1/user
tags:
  - name: Transactions
    description: Everything to do with banking transactions
security:
  - Bearer: []
paths:
  /transactions/{accountID}:
    get:
      tags:
        - Transactions
      summary: Return transactions from the bank account concerned
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: accountID
          schema:
            type: string
          required: true
          description: Account ID
      operationId: getTransactions
      responses:
        '200':
          description: Returns a list of transactions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfTransactions'
        '400':
          $ref: '#/components/responses/InvalidFields'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'
  /transaction/{transactionId}:
    get:
      tags:
        - Transactions
      summary: Return the relevant transaction
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      operationId: getTransaction
      responses:
        '200':
          description: Returns a transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
        '400':
          $ref: '#/components/responses/InvalidFields'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - Transactions
      summary: Modify a transaction
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: Attach Bearer JWT token
        - in: path
          name: transactionId
          schema:
            type: string
          required: true
          description: Transaction ID
      requestBody:
        description: Modify Transaction information
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    notes:
                      type: string
                - type: object
                  properties:
                    category:
                      type: string
      operationId: modifyTransaction
      responses:
        '200':
          description: Returns a transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transactions'
        '400':
          $ref: '#/components/responses/InvalidFields'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  schemas:
    Transactions:
      type: object
      properties:
        id:
          type: integer
        date:
          type: string
        description:
          type: string
        amount:
          type: number
        category:
          type: string
        notes:
          type: string
        transactionType:
          type: string
      example:
        id: 1
        date: 2024/05/28
        description: Golden Sun Bakery
        amount: 5
        category: Food
        notes: ''
        transactionType: electronic
    ArrayOfTransactions:
      type: array
      items:
        $ref: '#/components/schemas/Transactions'
      example:
        - id: 1
          date: 2024/05/28
          description: Golden Sun Bakery
          amount: 5
          category: Food
          notes: ''
          transactionType: electronic
        - id: 2
          date: 2024/05/29
          description: Golden Sun Bakery
          amount: 10
          category: Food
          notes: ''
          transactionType: electronic
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
    ServerError:
      description: Internal Server Error
    InvalidFields:
      description: Invalid Fields
securityDefinitions:
  Bearer:
    type: http
    scheme: bearer
    bearerFormat: JWT
